23 add limitations to username choice
melleg/twitbook pull request #27
Opened 2024-02-26 14:36 UTC by RaafiKuijper

2024-02-26 14:40 UTC, NolKeereweer requested changes

2024-02-26 14:40 UTC, NolKeereweer commented on backend/src/main/java/nl/itvitae/twitbook/security/AuthController.java
> +              "Username is invalid, should be between %d and %d characters long and only include alphabetical numerical characters or underscores",
, tje maybe

2024-02-26 14:41 UTC, melleg requested changes

2024-02-26 14:41 UTC, melleg commented on backend/src/main/java/nl/itvitae/twitbook/security/AuthController.java
> +        String.format("[\\w\\d_]{%d,%d}", MIN_USERNAME_LENGTH, MAX_USERNAME_LENGTH),
Good! Please add this Regex pattern to Globals.ts in the frontend and use it as `<input pattern={Globals.usernamePattern} />` in the RegisterComponent

2024-02-29 09:33 UTC, NolKeereweer approved these changes
Looking good!

2024-02-29 09:33 UTC, melleg approved these changes

2024-02-29 09:33 UTC, merged